# This is name of workflow that will be displayed on actions tab
name: CICD

# manual click whenever user needs 
on:
 workflow_dispatch: 
jobs:
  Code:
   runs-on: ubuntu-latest
   steps:
    - name: checkout code
      run: echo "code clone from github"
  Build:
   runs-on: ubuntu-latest
   steps:
    - name: build Docker container
      run: echo "Docker container build"
  Test:
   runs-on: ubuntu-latest
   steps:
    - name: Test container with tool 
      run: echo "Testing container sonar_qube"
  Packages:
   runs-on: ubuntu-latest
   steps:
    - name: Test container with tool 
      run: echo "Testing container sonar_qube"
  Release:
   runs-on: ubuntu-latest
   steps:
    - name: Envoriments specifice release 
      run: echo "One env to another env dev,stage,prod"  
  Configure:
   runs-on: ubuntu-latest
   steps:
    - name: Moniter
      run: echo "Sysdig for moniter L1,L2"
