---
#This is sarvesh workflow name
name: Sarvesh

on:
  push:
     branches: [main]

#these are jobs inside workflow
jobs:
   Greet:
     runs-on: ubuntu-latest
     steps:
        - name: say hello to users
          run: echo "Hello Sarvesh"      
   Details: 
     runs-on: ubuntu-latest
     steps:
        - name: collage of user
          run: echo "Shivaji University,kolhaur"
          
      
      
   
